services:
  templater:
    build: .
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]
    env_file:
      - .env
    ports:
      - ${port}:8000
    volumes:
      - ${data_path}:/app/data