services:
  templater:
    build: .
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${port}", "--proxy-headers"]
    ports:
      - ${port}:${port}
    env_file:
      - .env
    volumes:
      - ${data_path}:/app/data